git:
 depth: 1
cache: yarn
matrix:
  fast_finish: true
language: node_js
node_js:
  - "7"
notifications:
  email:
    - arnab@binary.com
    - amin@binary.com
branches:
  only:
    - master
script:
  - yarn build
